// @vitest-environment node
import { describe, expect, it } from 'vitest';
import path from 'node:path';
import {
  parseIni,
  listProfiles,
  defaultFromInstalls,
  resolveDefaultProfile,
} from './profiles-ini';

const PROFILES_INI_MODERN = `# Generated by Firefox

[Install4F96D1932A9F858E]
Default=Profiles/abcd1234.default-release
Locked=1

[Profile0]
Name=default-release
IsRelative=1
Path=Profiles/abcd1234.default-release

[Profile1]
Name=alternative
IsRelative=1
Path=Profiles/efgh5678.alternative
Default=1

[General]
StartWithLastProfile=1
Version=2
`;

const INSTALLS_INI = `[4F96D1932A9F858E]
Default=Profiles/abcd1234.default-release
Locked=1
`;

const PROFILES_INI_LEGACY = `[Profile0]
Name=default
IsRelative=1
Path=Profiles/legacy.default
Default=1
`;

const PROFILES_INI_NO_DEFAULT = `[Profile0]
Name=only
IsRelative=1
Path=Profiles/only.profile
`;

describe('parseIni', () => {
  it('parses sections, key=value lines, and trims whitespace', () => {
    const ini = parseIni(`
      [General]
        Version = 2
      [Profile0]
      Name=default-release
      IsRelative=1
    `);
    expect(ini.General.Version).toBe('2');
    expect(ini.Profile0.Name).toBe('default-release');
    expect(ini.Profile0.IsRelative).toBe('1');
  });

  it('ignores comments and empty lines', () => {
    const ini = parseIni(`
      # comment
      ; another
      [S]
      a=1
    `);
    expect(ini.S).toEqual({ a: '1' });
  });

  it('returns an empty object for empty input', () => {
    expect(parseIni('')).toEqual({});
  });
});

describe('listProfiles', () => {
  it('returns only sections starting with Profile', () => {
    const ini = parseIni(PROFILES_INI_MODERN);
    const profiles = listProfiles(ini);
    expect(profiles).toHaveLength(2);
    expect(profiles[0].name).toBe('default-release');
    expect(profiles[0].path).toBe('Profiles/abcd1234.default-release');
    expect(profiles[0].isRelative).toBe(true);
    expect(profiles[1].name).toBe('alternative');
    expect(profiles[1].isDefault).toBe(true);
  });

  it('skips sections without Path', () => {
    const ini = parseIni(`[Profile0]\nName=foo\n`);
    expect(listProfiles(ini)).toEqual([]);
  });
});

describe('defaultFromInstalls', () => {
  it('matches the installs.ini Default to a profile by Path', () => {
    const profilesIni = parseIni(PROFILES_INI_MODERN);
    const installsIni = parseIni(INSTALLS_INI);
    const profiles = listProfiles(profilesIni);
    const found = defaultFromInstalls(installsIni, profiles);
    expect(found?.name).toBe('default-release');
  });

  it('returns null when installs.ini references an unknown profile', () => {
    const profiles = listProfiles(parseIni(PROFILES_INI_MODERN));
    const installs = parseIni(`[XYZ]\nDefault=Profiles/missing.profile\n`);
    expect(defaultFromInstalls(installs, profiles)).toBeNull();
  });
});

describe('resolveDefaultProfile', () => {
  const baseDir = '/Users/test/Library/Application Support/Firefox';

  function makeReader(files: Record<string, string>) {
    return (p: string) => {
      if (p in files) return files[p];
      const err = new Error(`ENOENT: ${p}`) as NodeJS.ErrnoException;
      err.code = 'ENOENT';
      throw err;
    };
  }

  it('prefers installs.ini when both files are present', () => {
    const result = resolveDefaultProfile({
      profilesIniPath: path.join(baseDir, 'profiles.ini'),
      installsIniPath: path.join(baseDir, 'installs.ini'),
      baseDir,
      readFile: makeReader({
        [path.join(baseDir, 'profiles.ini')]: PROFILES_INI_MODERN,
        [path.join(baseDir, 'installs.ini')]: INSTALLS_INI,
      }),
    });
    expect(result?.source).toBe('installs.ini');
    expect(result?.profileDir).toBe(path.join(baseDir, 'Profiles/abcd1234.default-release'));
  });

  it('falls back to Default=1 when installs.ini is missing', () => {
    const result = resolveDefaultProfile({
      profilesIniPath: path.join(baseDir, 'profiles.ini'),
      installsIniPath: path.join(baseDir, 'installs.ini'),
      baseDir,
      readFile: makeReader({
        [path.join(baseDir, 'profiles.ini')]: PROFILES_INI_LEGACY,
      }),
    });
    expect(result?.source).toBe('profiles.ini-default');
    expect(result?.profileDir).toBe(path.join(baseDir, 'Profiles/legacy.default'));
  });

  it('falls back to first profile when no Default flag is present', () => {
    const result = resolveDefaultProfile({
      profilesIniPath: path.join(baseDir, 'profiles.ini'),
      installsIniPath: path.join(baseDir, 'installs.ini'),
      baseDir,
      readFile: makeReader({
        [path.join(baseDir, 'profiles.ini')]: PROFILES_INI_NO_DEFAULT,
      }),
    });
    expect(result?.source).toBe('first-profile');
    expect(result?.profileDir).toBe(path.join(baseDir, 'Profiles/only.profile'));
  });

  it('returns null when profiles.ini is missing', () => {
    const result = resolveDefaultProfile({
      profilesIniPath: path.join(baseDir, 'profiles.ini'),
      installsIniPath: path.join(baseDir, 'installs.ini'),
      baseDir,
      readFile: makeReader({}),
    });
    expect(result).toBeNull();
  });
});
